### ISSUE TITLE
[Bug] 트랜잭션 설정 범위

### ISSUE THREAD

**Issue by HyeonKyo** [so-sim/server#23]
name: Fix
about: 프로젝트 버그 수정 이슈
title: 'Fix'
labels: '🛠 fix'
---
## ⚙️ 버그 발생 위치
@Park-Jaemin 
Class : OAuthService

![image](https://github.com/so-sim/server/assets/76610333/1ba9fd5b-4dec-4104-8575-079776caced0)

## 🚨 버그 발생 상황
- Save, Update를 하는데 트랜잭션 최상단 설정이 read only입니다.

**Comment by Park-Jaemin** [comment]
해당 부분은 인지하고 있던 부분입니다.
서비스 자체에 readOnly를 걸어두었고 OAuth 단에서 임의로 DB를 조작할 수 없도록 막자라는 의미로 걸어두었습니다.
Save, Update는 UserService의 메서드에서 따로 관리 해두고 Transaction을 설정해둔 형태로 정상적으로 Save 및 Update가 이루어집니다.
![image](https://github.com/so-sim/server/assets/123621015/316cd29e-978a-4b5b-954a-a120c8fc1387)
